server:
  port: 9002

spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
#          uri: file://${user.home}/application-config
          uri: https://github.com/witsakon-si/application-config.git

eureka:
  client:
    service-url:
      defaultZone: http://localhost:9001/eureka
