server:
  port: 9002

spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: file://${user.home}/application-config

eureka:
  client:
    service-url:
      defaultZone: http://localhost:9001/eureka
